sudo: false
language: node_js
node_js:
  - 6
  - 8
  - 10
  - LTS/*

# Make sure we have new NPM.
before_install:
  - npm install -g npm

before_script:
  - npm install -g grunt-cli

script:
  - grunt
